### ISSUE TITLE
playground subscription doesn't listen with graphcool@next

### ISSUE THREAD

**Issue by miyi** [graphcool/graphql-playground#191]
I started a graphcool@next project with the initial User and Post model. I want to listen to subscriptions in the playground for the creation of posts and users, but i get blanks. The same thing happens with all graphcool subscription tutorials as well (freedom, worldchat, instagram).
<img width="1111" alt="screen shot 2017-10-19 at 3 40 57 pm" src="https://user-images.githubusercontent.com/6610928/31797621-1cbc93c0-b4e4-11e7-9c55-07d3696a1150.png">

I hard coded subscription endpoint shows "subscribe is undefined". The above picture happens when I change the subscription endpoint to the real one as shown in the CLI. Is subscription in the playground broken at the moment?

**Comment by miyi** [comment]
allposts show multiple posts created, but subscription listener is empty
<img width="1080" alt="screen shot 2017-10-19 at 3 47 23 pm" src="https://user-images.githubusercontent.com/6610928/31797775-fafd139e-b4e4-11e7-8c2d-6715cdb2ac57.png">

**Comment by kbrandwijk** [comment]
I can confirm it's also not working for me...

**Comment by timsuchanek** [comment]
Thanks for reporting! When clicking on the cog symbol, what does the
subscription endpoint say?

**Comment by Cerberus** [comment]
@timsuchanek I got the same problem. Subscription endpoint was empty and I cannot typed anything on the input box. Well, I saw an improper web-socket was called on the network tab(inspect element).
![screen shot](https://user-images.githubusercontent.com/9087409/31855143-e9afce2e-b6ce-11e7-81c1-6b91997dbc8c.png)

v1.0.2 on mac

**Comment by crubier** [comment]
Came to see if someone else had this bug. I am on v1.0.2 on a mac, running a local deployment, and cannot change the subscription endpoint.

**Comment by joshhopkins** [comment]
Have this issue too.

**Comment by morajabi** [comment]
It seems it's a critical issue. /cc @timsuchanek

**Comment by timsuchanek** [comment]
The subscriptions endpoint now is being configured with graphql config. You can read more about that here: https://github.com/graphcool/graphql-config#specifying-endpoint-info

The workflow looks like this:
Have a folder with `.graphqlconfig` file.
Execute `graphql playground`, `gc playground` or `prisma playground`, all work the same.
The according endpoint will be opened with subscriptions enabled.

If you have a prisma or graphcool project, you don't need to provide the endpoints by hand - they're deducted from the prisma.yml or graphcool.yml.
You just need to provide an "extension" in the graphql config:
```yml
projects:
  my-db:
    extensions:
      prisma: prisma.yml
      graphcool: graphcool.yml
```

Let me know if you have any issues with this workflow.
Reopen if this is not solving your issue.
Thanks!

**Comment by hoodsy** [comment]
@timsuchanek I'm having the same issue trying to test subscriptions through the `prisma/examples/subscriptions` example

`.graphqlconfig.yml`
```yml
projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
```
