### ISSUE TITLE
Subscriptions not working with different path

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/graphql-playground#462]
#### This issue pertains to the following package(s):

- [X] GraphQL Playground Express Middleware

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.4.3

#### What is the expected behavior?
If I specify a different subscriptionsendpoint, it should work.

#### What is the actual behavior?
It doesn't. It tries to connect to `/graphql` (my 'normal' endpoint)

#### What steps may we take to reproduce the behavior?

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by kbrandwijk** [comment]
This happens both in production mode (when I pass in the subscriptionendpoint using the options) _and_ in dev mode (when it's supposed to read it from `.graphqlconfig.yml`. This is my config:
```yml
extensions:
      endpoints:
        default: 
          url: 'http://localhost:5000/graphql'
          subscription: 'http://localhost:5000/subscriptions'
```

**Comment by gijo-varghese** [comment]
It's not reading the `.graphqlconfig.yml`. For me, queries and mutations are working fine. But subscriptions are not working. That's the only reason I don't use Playground. I was trying the express middleware.

**Comment by adamjking3** [comment]
Is there any fix for this?

**Comment by evseevnntmp** [comment]
any fix for this?

**Comment by lekterable** [comment]
Hey guys, actually it's not a bug. You're just not passing the subscription endpoint according to https://github.com/prisma/graphql-config

@kbrandwijk this would work in your case
```
extensions:
      endpoints:
        default: 
          url: 'http://localhost:5000/graphql'
          subscription:
             url: 'http://localhost:5000/subscriptions'
```
Project examples need a fix tho, they are also incorrect and probably misled you.
Hope this helps 😄
